apiVersion: v1
kind: Service
metadata:
  name: {{ include "bull-der-dash.fullname" . }}
  labels:
    {{- include "bull-der-dash.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "bull-der-dash.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
