{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "bull-der-dash.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "bull-der-dash.labels" . | nindent 4 }}
{{- end -}}
